name: Publish packages to ADO

on:
    push:
        branches:
            - ado_artifact_feed
        paths:
            - 'packages/package-1/**'
            - 'packages/package-2/**'
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        environment: ado_artifact_feed
        steps:
        - name: Checkout repository
          uses: actions/checkout@v2
          with:
            fetch-depth: 0  # Fetch all history for all branches and tags

        - name: Set up Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '20.x'

        - name: setup user .npmrc
          run: |
            echo "; begin auth token" >> ~/.npmrc
            echo "//pkgs.dev.azure.com/meshsystems/906251ef-583e-4dec-a809-f74c118f3cca/_packaging/Spirax.Demo/npm/registry/:username=meshsystems" >> ~/.npmrc
            echo "//pkgs.dev.azure.com/meshsystems/906251ef-583e-4dec-a809-f74c118f3cca/_packaging/Spirax.Demo/npm/registry/:_password=[BASE64_ENCODED_PERSONAL_ACCESS_TOKEN]" >> ~/.npmrc
            echo "//pkgs.dev.azure.com/meshsystems/906251ef-583e-4dec-a809-f74c118f3cca/_packaging/Spirax.Demo/npm/registry/:email=matt.ruiz@meshsystems.com" >> ~/.npmrc
            echo "//pkgs.dev.azure.com/meshsystems/906251ef-583e-4dec-a809-f74c118f3cca/_packaging/Spirax.Demo/npm/:username=meshsystems" >> ~/.npmrc
            echo "//pkgs.dev.azure.com/meshsystems/906251ef-583e-4dec-a809-f74c118f3cca/_packaging/Spirax.Demo/npm/:_password=[BASE64_ENCODED_PERSONAL_ACCESS_TOKEN]" >> ~/.npmrc
            echo "//pkgs.dev.azure.com/meshsystems/906251ef-583e-4dec-a809-f74c118f3cca/_packaging/Spirax.Demo/npm/:email=matt.ruiz@meshsystems.com" >> ~/.npmrc
            echo "; end auth token" >> ~/.npmrc
            cat ~/.npmrc
        
        - name: replace token in .npmrc
          run: |
            BASE64_ENCODED_PERSONAL_ACCESS_TOKEN=$(echo -n ${{ secrets.ADO_PAT }} | base64)
            sed -i "s/\[BASE64_ENCODED_PERSONAL_ACCESS_TOKEN\]/$BASE64_ENCODED_PERSONAL_ACCESS_TOKEN/g" ~/.npmrc
            cat ~/.npmrc

        - name: check git diff for packages
          id: git_diff_check
          run: |
            for dir in packages/*/; do
              package_name=$(basename "$dir")
              if git diff --name-only HEAD^ HEAD | grep -q "$dir"; then
                echo "${package_name}_CHANGED=true" >> $GITHUB_ENV
                echo "Changes detected in $package_name"
                echo "Github Env var name: ${package_name}_CHANGED"
              else
                echo "${package_name}_CHANGED=false" >> $GITHUB_ENV
                echo "No changes detected in $package_name"
              fi
            done

        - name: publish package-1
          if: env.package-1_CHANGED == 'true'
          working-directory: packages/package-1
          run: npm publish

        - name: publish package-2
          if: env.package-2_CHANGED == 'true'
          working-directory: packages/package-2
          run: npm publish