name: Publish packages to ADO

on:
    push:
        branches:
            - ado_artifact_feed
        paths:
            - 'packages/package-1/**'
            - 'packages/package-2/**'
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        environment: ado_artifact_feed
        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Set up Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '20.x'

        - name: setup user .npmrc
          run: |
            echo "; begin auth token" >> ~/.npmrc
            echo "//pkgs.dev.azure.com/meshsystems/906251ef-583e-4dec-a809-f74c118f3cca/_packaging/Spirax.Demo/npm/registry/:username=meshsystems" >> ~/.npmrc
            echo "//pkgs.dev.azure.com/meshsystems/906251ef-583e-4dec-a809-f74c118f3cca/_packaging/Spirax.Demo/npm/registry/:_password=[BASE64_ENCODED_PERSONAL_ACCESS_TOKEN]" >> ~/.npmrc
            echo "//pkgs.dev.azure.com/meshsystems/906251ef-583e-4dec-a809-f74c118f3cca/_packaging/Spirax.Demo/npm/registry/:email=matt.ruiz@meshsystems.com" >> ~/.npmrc
            echo "//pkgs.dev.azure.com/meshsystems/906251ef-583e-4dec-a809-f74c118f3cca/_packaging/Spirax.Demo/npm/:username=meshsystems" >> ~/.npmrc
            echo "//pkgs.dev.azure.com/meshsystems/906251ef-583e-4dec-a809-f74c118f3cca/_packaging/Spirax.Demo/npm/:_password=[BASE64_ENCODED_PERSONAL_ACCESS_TOKEN]" >> ~/.npmrc
            echo "//pkgs.dev.azure.com/meshsystems/906251ef-583e-4dec-a809-f74c118f3cca/_packaging/Spirax.Demo/npm/:email=matt.ruiz@meshsystems.com" >> ~/.npmrc
            echo "; end auth token" >> ~/.npmrc
            cat ~/.npmrc
        
        - name: replace token in .npmrc
          run: |
            BASE64_ENCODED_PERSONAL_ACCESS_TOKEN=$(echo -n ${{ secrets.ADO_PAT }} | base64)
            sed -i "s/\[BASE64_ENCODED_PERSONAL_ACCESS_TOKEN\]/$BASE64_ENCODED_PERSONAL_ACCESS_TOKEN/g" ~/.npmrc
            cat ~/.npmrc

        - name: check git diff for package-1 and package-2
          id: git_diff_check
          run: |
            git diff --name-only HEAD^ HEAD
            echo "::set-output name=diff::$(git diff --name-only HEAD^ HEAD)"
          
        - name: echo git diff
          run: echo ${{ steps.git_diff_check.outputs.diff }}